### ISSUE TITLE
touchmove相关问题

### ISSUE THREAD

**Issue by daiqiaojun** [eva-engine/eva.js#10]
1.手势不在当前物体上 move 也会触发。如给一个元素绑定move事件后，鼠标或者手势不在当前元素时仍会触发
2.多个元素绑定时，仅在一个元素内移动，其他元素也会触发move
3.EVA.plugin.renderer.event.js中container.on('pointermove', function (e) {}  e.target PC端有而移动端为null

**Comment by fanmingfei** [comment]
这个issue的评论看似可以解决问题：
https://github.com/pixijs/pixi.js/issues/4887#issuecomment-493796992

**Comment by daiqiaojun** [comment]
可否考虑用game.scene接受全局的交互行为，而每个元素的move仅对自身元素的move生效，如果要有跟随，可以将元素跟随逻辑放在game.scene的move事件里，可以参考引擎的demo
http://developer.egret.com/cn/example/egret2d/index.html#060-interact-drag-drop

**Comment by fanmingfei** [comment]
在 Event 系统里添加 `moveWhenInside` 参数是否可行？

**Comment by daiqiaojun** [comment]
根据作者提供的信息
1.使用game.scene接收全局交互行为
` var app = game.systems[0].application;
    app.renderer.plugins.interaction.moveWhenInside = true;
   var gameSceneEvt = game.scene.addComponent(
      new Event({
        hitArea: {
          type: HIT_AREA_TYPE.Rect,
          style: app.screen// 全屏热区
        }
      }),
    );
    gameSceneEvt.on('touchmove', e => {
      console.log('全屏移动'); // 可以将元素的拖拽逻辑放在全局上
    });
`

2.使用pixi的app.stage接收全局的交互行为
`    var app = game.systems[0].application;
    app.renderer.plugins.interaction.moveWhenInside = true;
    app.stage.interactive = true;
    app.stage.hitArea = app.screen
    app.stage.addListener('pointermove', () => {
      console.log('全屏移动');
    })`
对应的事件需要结合pixi的来使用了。
 app.renderer.plugins.interaction.moveWhenInside = true; 可以解决全屏move的情况，只在当前元素触发，且EVA.plugin.renderer.event.js中container.on('pointermove', function (e) {} e.target在PC端和移动端统一了。


pixi [v4](https://pixijs.io/examples-v4/#/interaction/dragging.js)版本存在touch相关的问题，[v5、v6](https://pixijs.io/examples/#/events/drag-n-drop.js)已经解决了，建议作者参考相关内容或做出修改
