### ISSUE TITLE
EvaX报错 无法添加入对象内

### ISSUE THREAD

**Issue by han-yao-long** [eva-engine/eva.js#100]
## 版本
` "@eva/plugin-evax": "^1.1.1",
    "@eva/plugin-renderer": "^1.1.0",
    "@eva/plugin-renderer-img": "^1.1.0",`
## 书写内容
`    const gameObject1 = new GameObject("bg1", {
      size: {
        width: 800,
        height: 1000,
      },
      position: { x: 0, y: 1000 }
    });
    gameObject1.addComponent(new EvaX({
      events: {
        'store.a': () => {}
      }
    }))`
## 报错
` addComponent recieve Component and Component Constructor`

**Comment by fanmingfei** [comment]
重装所有 npm 包。保持所有npm包版本保持一致
