### ISSUE TITLE
物理引擎问题

### ISSUE THREAD

**Issue by aspsnd** [eva-engine/eva.js#112]
### Current Behavior
- 合成大西瓜将isTest设置为false时两个水果合体会报错
![image](https://user-images.githubusercontent.com/46017470/130175106-fbc5dc14-67a7-4472-9110-674fb07643c8.png)
- 调用pause matter.js插件报错
![image](https://user-images.githubusercontent.com/4632277/130313948-61efadad-6635-4047-8963-1e188a322f5d.png)

- 没有时间change和remove方法 remove是要实现的

### Environment

- **`Eva.js` version**: _e.g. 1.0.0_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. MacOS 10.15.7_
- **Running Example**: _url_

**Comment by fanmingfei** [comment]
- 合成大西瓜将isTest设置为false时两个水果合体会报错
- 调用pause matter.js插件报错
- 没有时间change和remove方法 remove是要实现的
