### ISSUE TITLE
如何加载本地项目资源，例如json，本地图片？

### ISSUE THREAD

**Issue by huiruo** [eva-engine/eva.js#114]
### Expected Behavior
    resource.addResource([
        {
            name: 'imageName',
            type: RESOURCE_TYPE.IMAGE,
            src: {
                image: {
                    type: 'png',
                    url: 'https://gw.alicdn.com/tfs/TB1DNzoOvb2gK0jSZK9XXaEgFXa-658-1152.webp',
                    // url:'./test_png.webp',
                },
            },
            preload: true,
        },
    ]);

### Environment

- **`Eva.js` version**: _e.g. 1.0.0_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. MacOS 10.15.7_
- **Running Example**: _url_

**Comment by fanmingfei** [comment]
这和在正常页面中访问本地资源没有什么区别。eva.js不会对你输入的路径进行改变。

**Comment by ai-blib** [comment]
是根据你打包后，的资源相对路径来取的。

**Comment by huiruo** [comment]
> 是根据你打包后，的资源相对路径来取的。

懂了，我应该是放到未打包的路径导致读取不了
