### ISSUE TITLE
实现一个命令行工具或者客户端工具生成eva.js所需的压缩纹理

### ISSUE THREAD

**Issue by fanmingfei** [eva-engine/eva.js#149]
### Environment

- **`Eva.js` version**: _e.g. 1.0.0_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. MacOS 10.15.7_
- **Running Example**: _url_

**Comment by aspsnd** [comment]
请具体描述一下该工具的功能。 @fanmingfei

**Comment by aspsnd** [comment]
已完成，见[@eva/texture-compressor](https://github.com/eva-engine/texture-compressor)
