### ISSUE TITLE
开发和打包时的依赖报错

### ISSUE THREAD

**Issue by Congb19** [eva-engine/eva.js#15]
### 问题：vue3+ts+vite开发环境下报错

Uncaught ReferenceError: global is not defined      requestAnimationFrame.js:24
    at requestAnimationFrame.js:24

打包时也报了一些ts类型错误、pixi.js的错误

### Environment
- **`EVA.js` version**: 1.0.4
- **Browser & Version**: chrome90（arm64
- **OS & Version**: macos bigsur 11.2.3
- **Running Example**: 无法正常打包发布，555，https://github.com/Congb19/congb19-top/blob/main/src/pages/game.vue

**Comment by lidongjies** [comment]
vite 在开发环境使用的是 pixi.js 的源码，报错的 requestAnimationFrame.js 是 pixi.js 的 polyfill 之一，文件开头有这么一段注释

> Expected to be used with Browserfiy
> Browserify automatically detects the use of `global` and passes the
> correct reference of `global`, `self`, and finally `window`

browserify 自动处理 global、self 应用到 window 对象，但 vite 并没有对这个做处理，不知道 vite 有没有这样的配置。

目前你可以在 `index.html` 中加上 `window.global = globalThis` 来解决这个问题

**Comment by Congb19** [comment]
> window.global = globalThis

已解决，感谢

**Comment by cshenger** [comment]
> > window.global = globalThis
> 
> 已解决，感谢

我也是碰到这个问题，想了半天觉得来这里肯定能找到答案，哈哈哈
