### ISSUE TITLE
resource.destory()动态删除资源时报错（删除没有用到的资源）

### ISSUE THREAD

**Issue by WuZheXiao** [eva-engine/eva.js#169]
### Expected Behavior
resource.destory()，动态删除
### Current Behavior
删除resource.destory() 资源报错
![WX20211215-162252](https://user-images.githubusercontent.com/26809951/146150780-835ab5e3-5174-439b-bd8b-6a17e474f674.png)

### Possible Solution
是因为我还在用这个资源吗？我这边是用户长链接进来的一些头像、名称的资源，我想用户下去之后删除头像名称资源
### Steps to Reproduce
![WX20211215-162515](https://user-images.githubusercontent.com/26809951/146151118-0ccac7cc-dbbc-4fad-9a63-0e9763eb7666.png)
![image](https://user-images.githubusercontent.com/26809951/146151252-adde4bb9-795e-471f-ad0d-68e0d5445faf.png)

### Environment

- **`Eva.js` version**: _e.g. 1.1.6_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. MacOS 10.15.7_
- **Running Example**: _url_

**Comment by fanmingfei** [comment]
[playground](https://eva.js.org/playground/#/image)
在这上面写一个简单能够复现的demo发出来吧

**Comment by WuZheXiao** [comment]
> 
大佬，用resource.destory()的时候是不是一定要这个资源complete等于false的时候才可以删啊

**Comment by fanmingfei** [comment]
> > 
> 
> 大佬，用resource.destory()的时候是不是一定要这个资源complete等于false的时候才可以删啊

不是啊

**Comment by fanmingfei** [comment]
只要没有被使用 都可以删。

**Comment by fanmingfei** [comment]
![image](https://user-images.githubusercontent.com/4632277/146739631-2c78d51d-f1b7-468e-b71f-0062b2aa0f15.png)
虽然 image 对象不是同一个对象，其实他底层用的baseTexture是同一个，因为PIXI的baseTexture是以url做cache的
所以 image1 image2 如果是同一个 url 的话，pixiBaseTexture 会认为是同一个资源，多个地方使用销毁一个另外一个也会被销毁

**Comment by WuZheXiao** [comment]
嗯嗯，我就是钉钉那个，你把这个bug关了吧 哈哈哈
