### ISSUE TITLE
编辑器相关需求

### ISSUE THREAD

**Issue by fanmingfei** [eva-engine/eva.js#181]

**Comment by fanmingfei** [comment]
添加游戏对象到指定的位置

```js
// 指定index
go.addChildAt(child, index)

```

**Comment by fanmingfei** [comment]
Transform中提供获取 Local Transform 和 Global Transform 的方案。

**Comment by ChinDer** [comment]
`async add(changed: ComponentChanged) {
    this.manager = new AnimationManager(this.app);
    const component = changed.component as Lottie;
    const container = this.renderSystem.containerManager.getContainer(changed.gameObject.id);
    if (!container) return;
    const { resource: rn, ...otherOpts } = component.options;
    const { data } = await resource.getResource(rn);
    const json = { ...(data.json || {}) };
    const assets = json.assets || [];`
LottieSystem add的时候。 resource.getResource(rn);可能为空 会导致data.json报错 需要兼容

**Comment by ChinDer** [comment]
` 
const { data } = await resource.getResource(rn);
 const json = { ...(data.json || {}) }; const assets = json.assets || [];
`
LottieSystem add的时候。 resource.getResource(rn);可能为空 会导致data.json报错 需要兼容
