### ISSUE TITLE
如何实现游戏对象的碰撞检测

### ISSUE THREAD

**Issue by linxu** [eva-engine/eva.js#20]
文档中未找到如何实现游戏对象的碰撞检测，Sprite是否有该方法？

**Comment by fanmingfei** [comment]
可以使用 MatterJS 插件，MatterJS 是基于2d的物理引擎。
这个是基于 MatterJS 实现的合成大西瓜
GitHub: https://github.com/eva-engine/wantermelon
GitPage: https://eva.js.org/wantermelon/

MatterJS 插件文档: https://eva-engine.gitee.io/#/tutorials/matterJS

**Comment by linxu** [comment]
Cool, Thanks.
