### ISSUE TITLE
通过game.loadScene添加了scene之后，scene.destroy()无限循环报错

### ISSUE THREAD

**Issue by ZhangYang-hand** [eva-engine/eva.js#203]
### Environment

- **`Eva.js` version**: _e.g. 1.0.0_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. MacOS 10.15.7_
- **Running Example**: _url_

**Comment by fanmingfei** [comment]
可以添加一下浮现步骤 重新打开issue
