### ISSUE TITLE
多scene下，stats 插件导致渲染异常（白屏）

### ISSUE THREAD

**Issue by ifengzp** [eva-engine/eva.js#204]
### Expected Behavior

stats插件和scene无关

### Current Behavior

多scene场景中，`@eva/plugin-stats` 插件影响到画面渲染，表现为：画面渲染空白，但是sys中的相关逻辑正常执行，点击画面中的元素能正常触发事件（仅仅是画面渲染失败）

### Environment
- **`Eva.js` version**: v 1.2.7
- **Browser & Version**:  all
- **OS & Version**:  MacOS 12.1
- **Running Example**: _url_

**Comment by fanmingfei** [comment]
@574495412 在 #178 中没有考虑到多个canvas的情况。
