### ISSUE TITLE
微信小游戏里如何引用了eva.js了

### ISSUE THREAD

**Issue by ninglei1993** [eva-engine/eva.js#216]
### Environment

- **`Eva.js` version**: _e.g. 1.0.0_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. MacOS 10.15.7_
- **Running Example**: _url_

**Comment by fanmingfei** [comment]
使用这个库来创建：
https://github.com/eva-engine/eva-multi-platform-demo

**Comment by ninglei1993** [comment]
感谢大佬回复，目前只能通过这个库来创建微信小游戏工程吗?  是否可以在小游戏空工程里直接通过npm安装eva.js呢

**Comment by fanmingfei** [comment]
> 感谢大佬回复，目前只能通过这个库来创建微信小游戏工程吗? 是否可以在小游戏空工程里直接通过npm安装eva.js呢

目前只能用这个库和这个脚手架。因为他需要将cdn上的文件下载下来使用。
