### ISSUE TITLE
骨骼动画Spine，切换第二个源的时候，产生残影的Bug

### ISSUE THREAD

**Issue by benweng** [eva-engine/eva.js#217]
### Expected Behavior
骨骼动画Spine，切换第二个源的时候，正常的spine

### Current Behavior
骨骼动画Spine，切换第二个源的时候，产生残影的Bug

### Possible Solution
切换第二个源的时候，还是第一个源的信息

### Environment
uniapp中的renderjs环境

截图：
![b3ef486472d15bb434d8cf7febe8be1](https://user-images.githubusercontent.com/10015855/203317870-1c5d241c-ba96-404a-9f98-84aef624ab1a.jpg)

![56dc42e8bc6d987b7bf8de691df057f](https://user-images.githubusercontent.com/10015855/203317885-9c831cd7-7238-44dc-a71d-abdd5ba7579b.jpg)

静态资源：
[static.zip](https://github.com/eva-engine/eva.js/files/10067473/static.zip)

主代码：
[AnimAmy.zip](https://github.com/eva-engine/eva.js/files/10067477/AnimAmy.zip)

- **`Eva.js` version v1.3.0-alpha.1
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. MacOS 10.15.7_
- **Running Example**: _url_

**Comment by fanmingfei** [comment]
可以尝试重新创建Spine组件，把之前的Spine组件替换掉。

**Comment by benweng** [comment]
> 可以尝试重新创建Spine组件，把之前的Spine组件替换掉。
请问是怎么替换之前的呢？替换游戏对象上面的哪个属性呢？components 对象替换之后也没有效果哦！

**Comment by benweng** [comment]
> 可以尝试重新创建Spine组件，把之前的Spine组件替换掉。

在chrome里面，只使用spine.resource = xxx是正常的

**Comment by fanmingfei** [comment]
> > 可以尝试重新创建Spine组件，把之前的Spine组件替换掉。
> 
> 在chrome里面，只使用spine.resource = xxx是正常的
```
gameObject.removeComponent(Spine)
const newSpine = new Spine({...})
gameObject.addComponent(newSpine)
```

**Comment by benweng** [comment]
> > > 可以尝试重新创建Spine组件，把之前的Spine组件替换掉。
> > 
> > 
> > 在chrome里面，只使用spine.resource = xxx是正常的
> 
> ```
> gameObject.removeComponent(Spine)
> const newSpine = new Spine({...})
> gameObject.addComponent(newSpine)
> ```

就是这样替换的，还是不行！感觉第一次的Spine都定死了，第二个即使替换也无法正常渲染，还有其他方法么？

**Comment by fanmingfei** [comment]
> > > > 可以尝试重新创建Spine组件，把之前的Spine组件替换掉。
> > > 
> > > 
> > > 在chrome里面，只使用spine.resource = xxx是正常的
> > 
> > 
> > ```
> > gameObject.removeComponent(Spine)
> > const newSpine = new Spine({...})
> > gameObject.addComponent(newSpine)
> > ```
> 
> 就是这样替换的，还是不行！感觉第一次的Spine都定死了，第二个即使替换也无法正常渲染，还有其他方法么？

正常这么换 是没问题的：
https://codesandbox.io/s/elated-faraday-vcbyh8?file=/src/components/HelloWorld.vue

**Comment by benweng** [comment]
> > > > > 可以尝试重新创建Spine组件，把之前的Spine组件替换掉。
> > > > 
> > > > 
> > > > 在chrome里面，只使用spine.resource = xxx是正常的
> > > 
> > > 
> > > ```
> > > gameObject.removeComponent(Spine)
> > > const newSpine = new Spine({...})
> > > gameObject.addComponent(newSpine)
> > > ```
> > 
> > 
> > 就是这样替换的，还是不行！感觉第一次的Spine都定死了，第二个即使替换也无法正常渲染，还有其他方法么？
> 
> 正常这么换 是没问题的： https://codesandbox.io/s/elated-faraday-vcbyh8?file=/src/components/HelloWorld.vue

切换第二个的时候还是残影，加载数据的时候用了type:"data",data:""，跟这个有关系么？

**Comment by benweng** [comment]
> > > > > 可以尝试重新创建Spine组件，把之前的Spine组件替换掉。
> > > > 
> > > > 
> > > > 在chrome里面，只使用spine.resource = xxx是正常的
> > > 
> > > 
> > > ```
> > > gameObject.removeComponent(Spine)
> > > const newSpine = new Spine({...})
> > > gameObject.addComponent(newSpine)
> > > ```
> > 
> > 
> > 就是这样替换的，还是不行！感觉第一次的Spine都定死了，第二个即使替换也无法正常渲染，还有其他方法么？
> 
> 正常这么换 是没问题的： https://codesandbox.io/s/elated-faraday-vcbyh8?file=/src/components/HelloWorld.vue

在浏览器中是没有问题的，就是在uniapp的renderjs中就是不行，切换第二个一直都是残影

**Comment by fanmingfei** [comment]
> > > > > > 可以尝试重新创建Spine组件，把之前的Spine组件替换掉。
> > > > > 
> > > > > 
> > > > > 在chrome里面，只使用spine.resource = xxx是正常的
> > > > 
> > > > 
> > > > ```
> > > > gameObject.removeComponent(Spine)
> > > > const newSpine = new Spine({...})
> > > > gameObject.addComponent(newSpine)
> > > > ```
> > > 
> > > 
> > > 就是这样替换的，还是不行！感觉第一次的Spine都定死了，第二个即使替换也无法正常渲染，还有其他方法么？
> > 
> > 
> > 正常这么换 是没问题的： https://codesandbox.io/s/elated-faraday-vcbyh8?file=/src/components/HelloWorld.vue
> 
> 在浏览器中是没有问题的，就是在uniapp的renderjs中就是不行，切换第二个一直都是残影

那就奇怪了。重新创建一个GameObject 呢？

**Comment by benweng** [comment]
> > > > > > > 可以尝试重新创建Spine组件，把之前的Spine组件替换掉。
> > > > > > 
> > > > > > 
> > > > > > 在chrome里面，只使用spine.resource = xxx是正常的
> > > > > 
> > > > > 
> > > > > ```
> > > > > gameObject.removeComponent(Spine)
> > > > > const newSpine = new Spine({...})
> > > > > gameObject.addComponent(newSpine)
> > > > > ```
> > > > 
> > > > 
> > > > 就是这样替换的，还是不行！感觉第一次的Spine都定死了，第二个即使替换也无法正常渲染，还有其他方法么？
> > > 
> > > 
> > > 正常这么换 是没问题的： https://codesandbox.io/s/elated-faraday-vcbyh8?file=/src/components/HelloWorld.vue
> > 
> > 
> > 在浏览器中是没有问题的，就是在uniapp的renderjs中就是不行，切换第二个一直都是残影
> 
> 那就奇怪了。重新创建一个GameObject 呢？

也尝试过，也是不行，我把整个gameObject都删除了，然后重新加一个进去也不行，不知道咋回事了！！！大佬可以用uniapp的renderjs试一试么
