### ISSUE TITLE
Sound音频系统如何切换音乐

### ISSUE THREAD

**Issue by Damons7** [eva-engine/eva.js#221]
Sound音频系统如何切换音乐，
是把前面的音乐销毁后创建新的音乐播放还是直接资源替换，相关的api是哪个？（顺带一问，音乐系统使用game.scene.addComponent(new Sound())后，如何获取对应的音频对象）

**Comment by fanmingfei** [comment]
Sound音频系统如何切换音乐: 可以多创建几个Sound，停掉了一个，播放另外一个。
你说的音频对象是什么？
这样可以拿到声音的组件
```js
const bgSound = bgSoundObj.addComponent(
  new Sound({ resource: 'bgSound', loop: true, autoplay: true, volume: 0.5 })
);
```
如果你想拿到资源对应的ArrayBuffer：
```js
import { SoundSystem } form '@eva/plugin-sound'

const audioBufferCache = game.getSystem(SoundSystem).audioBufferCache
```

**Comment by Damons7** [comment]
感谢回复，就是我是把音频直接加入了场景里了没有加入游戏对象（因为需要切换场景的时候能继续使用），所以直接使用game.scene.addComponent(new Sound())创建了，但之后使用的时候如何找到它这个对象（比如getComponent之类的方式）并进行暂停、禁用等操作呢

**Comment by Damons7** [comment]
或者说我能不能用game.scene.addComponent(new Sound())这种方式创建音频，这种方式如何创建多个音频

**Comment by fanmingfei** [comment]
可以。每个GameObject只能存放一个同样类型的组件，所以你需要创建多个GameObject 去存放多个Sound。这样的话 addComponent 的时候 其实就可以拿到每个Sound了。

**Comment by fanmingfei** [comment]
如果有其他问题可以联系我的VX: bWF5ZGF5ZmFudGFzdA==

**Comment by Damons7** [comment]
好的十分感谢问题解决了！但是大佬你的微信搜索不到hhh

**Comment by fanmingfei** [comment]
那是base64后的
