### ISSUE TITLE
中英文 文档不对应，中文文档错误明显

### ISSUE THREAD

**Issue by liuyonghu** [eva-engine/eva.js#223]
可以 对比 [中文文档](https://eva-engine.gitee.io/docs/tutorials/quickstart/#%E6%B7%BB%E5%8A%A0%E6%B8%B8%E6%88%8F%E5%AF%B9%E8%B1%A1) 和 [英文文档](https://eva.js.org/docs/tutorials/quickstart/#add-gameobject)

**Comment by fanmingfei** [comment]
修复中...

**Comment by swdcode** [comment]
现在中文官网都挂了   还行不行啊

**Comment by fanmingfei** [comment]
> 现在中文官网都挂了 还行不行啊

修复了，不过要从英文文档进。https://eva.js.org/zh-cn/
