### ISSUE TITLE
 导入eva其他组件时控制台 报错ReferenceError: global is not defined ？ 

### ISSUE THREAD

**Issue by JuYiYang** [eva-engine/eva.js#226]
### 控制台报错client.ts:113 ReferenceError: global is not defined

只要导入@eva/plugin-renderer（version:^1.2.8） / @eva/plugin-renderer-img(version:^1.2.8) 控制台就会报错global is not defined

项目 ： vite + vue3 + ts
- **`Eva.js` version**: ^1.2.8

**Comment by fanmingfei** [comment]
要不把global赋值一下
window.global = window

**Comment by JuYiYang** [comment]
> 要不把global赋值一下 window.global = window

可以了，貌似是Pixi库的问题
