### ISSUE TITLE
帧动画的forwards属性设置为true,没有效果

### ISSUE THREAD

**Issue by swdcode** [eva-engine/eva.js#229]
### Expected Behavior
new SpriteAnimation({
        resource: 'fruit',
        speed: 50,
        forwards: true,
      })
官方https://eva.js.org/playground/#/spriteAnimation 直接设置也是无效,自己的项目用的是最新的版本

"@eva/eva.js": "^1.2.8",
    "@eva/plugin-renderer": "^1.2.8",
    "@eva/plugin-renderer-graphics": "^1.2.8",
    "@eva/plugin-renderer-img": "^1.2.8",
    "@eva/plugin-renderer-lottie": "^1.2.8",
    "@eva/plugin-renderer-mask": "^1.2.8",
    "@eva/plugin-renderer-render": "^1.2.8",
    "@eva/plugin-renderer-sprite": "^1.2.8",
    "@eva/plugin-renderer-sprite-animation": "^1.2.8",
    "@eva/plugin-renderer-text": "^1.2.8",
    "@eva/plugin-transition": "^1.2.8",

**Comment by fanmingfei** [comment]
spritAnimation.play(1)

设置执行几次，执行完成后停止

**Comment by swdcode** [comment]
> spritAnimation.play（1）
> 
> 设置执行几次，执行完成后停止

好的  谢谢

**Comment by fanmingfei** [comment]
https://github.com/eva-engine/eva-engine.github.io/commit/61c7c5ed78598c2e6b1a078c86eafe6eb4b1aaf6
