### ISSUE TITLE
帧动画complete事件为什么currentFrame当前帧数不是最后一帧

### ISSUE THREAD

**Issue by swdcode** [eva-engine/eva.js#230]
帧动画complete事件为什么currentFrame当前帧数不是最后一帧
```js
frame.on('complete', res => {
        imgIndex++;
        if(imgIndex>9){
          imgIndex = 1;
        }       
        console.info('complete currentFrame',frame.currentFrame)
        console.info('complete totalFrames',frame.totalFrames)
      })
```

![微信截图_20240703101450.png](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f746188b137a4638a39134849f01dcc8~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=414&h=131&s=25531&e=jpg&b=fbf7ef)

**Comment by fanmingfei** [comment]
计数应该是从0开始的

**Comment by swdcode** [comment]
> 计数应该是从0开始的

请问,如果我的精灵图太大   我拆分成了多组,我如何能丝滑的使用帧动画。 一开始制作的精灵图只有1张，移动端渲染不出来，只有拆分了，但是不知道怎么多组连续播放

**Comment by fanmingfei** [comment]
历史遗留问题，不支持多组的播放模式。

**Comment by fanmingfei** [comment]
可以通过 降低帧率 压缩图片 来解决

**Comment by swdcode** [comment]
> 可以通过 降低帧率 压缩图片 来解决

谢谢
