### ISSUE TITLE
addComponent(new Event()) 报错

### ISSUE THREAD

**Issue by ipengkai** [eva-engine/eva.js#62]
### Current Behavior
![image](https://user-images.githubusercontent.com/25891640/124107963-54f29400-da98-11eb-858b-69b7a614a3ce.png)
代码：const evt = po.addComponent( new Event() ) 只要已执行这一句就会报错；

### Environment

- **`Eva.js` version**: _e.g. 1.0.0_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. MacOS 10.15.7_
- **Running Example**: _url_

**Comment by fanmingfei** [comment]
发生报错的原因是因为 Event 不是继承于 Component。
检查 Event 是否是 从 `@eva/plugin-renderer-event` 引入的
检查是否引用了相同的 `@eva/eva.js`, `npm update` 重装所有 `node_modules` 测试

**Comment by ipengkai** [comment]
卸载1.0.8，安装1.0.6版本就可以了。

**Comment by fanmingfei** [comment]
1.0.7版本都不行吗？你都用了哪些插件，可以看看你package.json么。
