### ISSUE TITLE
PhysicsSystem 初始化报错

### ISSUE THREAD

**Issue by ChinDer** [eva-engine/eva.js#68]
### Expected Behavior
正常初始化
### Current Behavior
Cannot read property 'bodyB' of undefined

### Possible Solution
初始化时候取消mouse: true参数
![image](https://user-images.githubusercontent.com/20189183/125245848-a49c4f80-e323-11eb-99a3-20ad0b6fb170.png)

### Environment

- **`Eva.js` version**: _e.g. 1.0.9
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. MacOS 10.15.7_
- **Running Example**: _url_

**Comment by aspsnd** [comment]
临时先把mouse参数去掉
