### ISSUE TITLE
lottie动画无法设置宽高

### ISSUE THREAD

**Issue by waqq** [eva-engine/eva.js#72]
看到构造函数的参数中可传width和height，传入后无效

截图是文档中的lottie动画 设置了宽高都是100 
文档：https://eva-engine.gitee.io/#/tutorials/lottieAnimation
代码：const lottieComponent = new Lottie({ resource: 'homeBg1', width: 100, height: 100 });

![image](https://user-images.githubusercontent.com/31087647/125768435-5fbccda1-446e-408f-ac2c-8782506e1023.png)

**Comment by fanmingfei** [comment]
使用scale来调整尺寸
