### ISSUE TITLE
直接复制lottie部分的官方demo代码，并没有办法出现lottie，并且也不会去加载lottie的json资源

### ISSUE THREAD

**Issue by strawberry3269** [eva-engine/eva.js#73]
### Expected Behavior
出现lottie播放的场景

### Environment
import { Game, GameObject, resource } from '@eva/eva.js'
import { RendererSystem } from '@eva/plugin-renderer'
import { LottieSystem, Lottie } from '@eva/plugin-renderer-lottie'

const game = new Game({
  systems: [
    new RendererSystem({
      canvas: document.querySelector('#canvas'),
      width: 750,
      height: 1624
    }),
    new LottieSystem()
  ],
  autoStart: true,
  frameRate: 60
})

resource.addResource([
  {
    name: 'ResourceName',
    type: 'LOTTIE',
    src: {
      json: {
        type: 'json',
        url: 'https://gw.alipayobjects.com/os/bmw-prod/61d9cc77-12de-47a7-b6e5-06c836ce7083.json'
      }
    }
  }
])

const LottieComponent = new Lottie({ resource: 'ResourceName' })
const LottieGameObject = new GameObject('ResourceName', {})

LottieGameObject.addComponent(LottieComponent)
game.scene.addChild(LottieGameObject)

- **`Eva.js` version**: _e.g. 1.0.0_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. MacOS 10.15.7_
- **Running Example**: _url_
-  "@eva/plugin-renderer-lottie": "^1.0.10",

**Comment by fanmingfei** [comment]
https://github.com/eva-engine/eva-engine.github.io/commit/ee96dad627b1bdfa7ffcfd65b75f160d9aed7b7f
