### ISSUE TITLE
examples eva script path is wrong

### ISSUE THREAD

**Issue by zhaoleipeng** [eva-engine/eva.js#8]
![image](https://user-images.githubusercontent.com/15973504/115847747-d523ca00-a455-11eb-8371-2837bd590a2b.png)
script path is wrong
please fix.

by the way
replace the path to /dist/cdn path also has problem

**Comment by fanmingfei** [comment]
Example maybe not must run with dev. @lidongjies

**Comment by lidongjies** [comment]
@zhaoleipeng @fanmingfei 

There are two ways to check the examples.

- use `http-server -o /examples/ -c-1` or `npm run server` to run a **static server**,  they are the same. 
- use `npm run dev` to run a **dev server**.

Both ways can automatically open indexes page in the default browser.

**Comment by lidongjies** [comment]
@zhaoleipeng  For now, some resources are currently blocked due to cross-domain policies. you should add `127.0.0.1 local.tmall.com` in you hosts fille. I will fix this problem as soon as possible

**Comment by zhaoleipeng** [comment]
ok
